# Theme
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "Sam's Site"
languageCode = "en-us"
baseURL = "https://samduane.com/"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  github = "https://github.com/samduane"
  email = "mailto:samduane@gmail.com"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Email", "GitHub"]

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"

[[menu.main]]
  identifier = "photos"
  name = "photos"
  title = "Photos"
  url = "https://photos.samduane.com"

[markup.goldmark.renderer]
  unsafe = true
